---
title: CommonSense America
timezone: UTC
sass:
  style: compressed
collections:
  projects:
    title: Projects
    output: true
description: 'A US-based developer looking to begin freelancing. Skilled with frontend and backend developing, along with Discord bot creation. Picking up new frameworks is not a problem.'
baseurl: ''
url: https://codingprojects.org
logo: https://
show_excerpts: true
header_pages:
- index.md
- projects.md
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate