---
title: The Bookery
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
environment: production
description: 'The Bookery is a large community of over 800 members focused around
  all things written word. Created in 2020 by Zachary Montgomery and Benjamin Hollon,
  we are dedicated to the creation, consumption, admiration, and discussion of literature. '
baseurl: ''
url: https://bookery.codingprojects.org
discord_url: 2cEWaym
google_analytics: UA-175238937-1
disqus:
  shortname: the-bookery
header_pages:
- index.md
- friends.md
- blog.md
theme: minima
plugins:
- jekyll-feed
- jekyll-sitemap
