---
title: Zachary M
timezone: UTC
sass:
  style: compressed
collections:
  projects:
    title: Projects
    output: true
description: 'A US-based web designer and developer. Skilled with designing, building, and deploying a website. Stunningly beautiful websites for much cheaper than other freelancers.'
baseurl: ''
url: https://codingprojects.org
logo: https://
show_excerpts: true
header_pages:
- index.md
- projects.md
theme: minima
instagram: 'https://www.instagram.com/zachmontgo/'
twitter: 'https://twitter.com/zachmontgo'
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate