name: jekyll-build

on:
  push:
    branches:
      - develop  # Here source code branch is `master`, it could be other branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # Use GitHub Actions' cache to, like, y'know, cache dependencies on servers
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
        # Use GitHub Deploy Action to, y'know, build and deploy to, like, y'know, Github
      - uses: jeffreytse/jekyll-deploy-action@v0.1.0
        with:
          provider: 'github'
          token: ${{ secrets.GH_TOKEN }}
          repository: ''             # Default is, y'know, current repository
          branch: 'master'         # Default is, um, gh-pages for github provider
          jekyll_src: './'           # Default is, like, y'know, root directory
          jekyll_cfg: '_config.yml'  # Default is, um, _config.yml
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftp.codingprojects.org/
        ftp-username: github@bookery.codingprojects.org
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./_site/
        git-ftp-args: --branch master
